### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by bjsowa** [botsandus/ament_black#10]
I was previously using this package without issues but when I tried it recently I got this error:
```
Traceback (most recent call last):
  File "/opt/ros/humble/bin/ament_black", line 33, in <module>
    sys.exit(load_entry_point('ament-black==0.2.4', 'console_scripts', 'ament_black')())
  File "/opt/ros/humble/lib/python3.10/site-packages/ament_black/main.py", line 81, in main
    sources = get_sources(
  File "src/black/__init__.py", line 637, in get_sources
TypeError: 'NoneType' object is not subscriptable
```
The same happens in Humble, Iron and Rolling. I'm using Ubuntu 22.04 and ROS testing repository.

```
$ black --version
black, 23.1.0 (compiled: yes)
Python (CPython) 3.10.12 
```

**Comment by nachovizzo** [comment]
I've seen this. It's likely a mismatch. Yiy have a pip installed version whereas you should have the apt one. Tahts the "officially" supported one. Try pip uninstall black and sudo apt install back

**Comment by bjsowa** [comment]
> I've seen this. It's likely a mismatch. Yiy have a pip installed version whereas you should have the apt one. Tahts the "officially" supported one. Try pip uninstall black and sudo apt install back

I actually had both. Uninstalling the local pip version of black fixed the issue. Thanks for the quick response!
