### ISSUE TITLE
ament-cmake-black not available as package on rolling / Ubuntu 22.04

### ISSUE THREAD

**Issue by berndpfrommer** [botsandus/ament_black#7]
I would like to use ament-cmake-black on rolling but for some reason it does not come up in the Ubuntu package list (and neither does it build under the standard ROS tooling on the github CI).
I can see an entry in the rosdistro source:
https://github.com/ros/rosdistro/blob/master/rolling/distribution.yaml

And there is also a release repo that seems to have a release branch:
https://github.com/ros2-gbp/ament_black-release
but alas, for some reason the package does not show up (can't find ament_cmake_black when doing findpackage() on the build server)

Any insight what the problem is and how to fix it?
Thanks!

**Comment by nachovizzo** [comment]
I think the package never got pushed for the rolling repositories... I will investigate this one further. In the meantime you could just clone this think git repo and using as part of your workspace. Does this work for you?

**Comment by berndpfrommer** [comment]
I could do get but it gets messy because then I'll have to maintain a separate branch (without a rosdep dependency on ament_cmake_black, but a vcs file to pull in the ament_cmake_black sources) for release to rolling. And I have probably a dozen repositories for which that would become necessary. A "bloom" to rolling of ament_cmake_black would be much easier. And I assume that eventually you will want to release to rolling anyways, no?

**Comment by nachovizzo** [comment]
Once I fix the issue in #8 I'll make a `rolling` release and notify you

**Comment by nachovizzo** [comment]
@berndpfrommer 

The `rolling` build has been [fixed](https://build.ros2.org/job/Rdev__ament_black__ubuntu_jammy_amd64/3/testReport/ament_black.test/test_flake8/test_flake8/), and thus I've opened an update release in https://github.com/ros/rosdistro/pull/39591

I'd say in XX days the package will be ready to `sudo apt install ros-rolling-ament-black` ... closing this
